POST http://localhost:8080/inventaire/createAdmin
Content-Type: application/json

{
    "email":"belfathiy@gmail.com",
    "password":"18346",
    "telephone":"023569",
    "nom_complet":"yassir belfathi",
    "poste_travail":"informatique",
    "type_user":"administrateur"
}

#ici on peut simplement changer l'id 44 par celui qui existe dans la table administrateur
#ou ce lui qui existe dans la table utilisateur, mais vous devez d'abord ajouter les informations
#avant de les supprimer
DELETE http://localhost:8080/inventaire/deleteAdmin/44