POST http://localhost:8080/inventaire/utilisateur/create
Content-Type: application/json

{
    "email":"belfathiy@gmail.com",
    "password":"18346",
    "telephone":"023569",
    "type_user":"utilisateur",
    "nom_complet":"yassir belfathi"
}